### ISSUE TITLE
별빛 무한로딩(제기불능)

### ISSUE THREAD

**Issue by IntelPentium0** [mooner1022/StarLight#23]
사건의 경위
1. 댓글을 보고 재부팅
2. 하지만 2번 보내지는 현상은 해결이 안됨
3. 이 시점부터 이상한 현상이 발생
--이벤트가 발생함에도 불구하고 답장이 안되는 현상
--이벤트가 발생한 방에 아닌 다른방에 시간차를 두고 2번 답장을 하는 현상
4.이상함을 느껴 재컴파일을 위해 별빛에 들어가려 했으나 노란 창만 뜨고 아무터치도 안먹히다가 틩김(노랑창은 밑의 사진입니다)
![Screenshot_20230826-200849_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/e41ad986-2cda-43ec-9b49-8d6e42d50a82)
5.안드로이드 시스템에서 별빛에 버그발생을 감지해 캐시를 삭제하라해서 약 400kb정도의 캐시를 삭제함
6.이후 20분이 지나도 로딩만 반복되는 무한로딩에 걸림
![Screenshot_20230826-200948_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/2d8a9246-220e-4aec-b153-cb22de1d0c69)
7.답답해서 최후의 수단으로 강제종료를 시켰으나 강종을 하자마자 해당 사진이 뜸
![Screenshot_20230826-202453_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/ec044e91-b130-411a-acfd-8368e05e277b)
8.앱 종료후 다시 실행시켜도 무한로딩만 반복함
-------------------------------------------------------------------------------------------
해당 오류 로그 전문입니다.

*** 치명적인 오류가 발생했습니다. 앱을 종료하는 중... ***
[버그 제보시 아래 메세지를 첨부해주세요.]
──────────
StarLight v0.1.0a-230820(build 1)
PluginCore v0.1.0
Build.VERSION.SDK_INT: 31
Build.DEVICE: a31
thread  : main
message : no event down from INITIALIZED
cause   : null
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.IllegalStateException: no event down from INITIALIZED
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:142)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at dev.mooner.starlight.plugincore.widget.Widget.onStateChanged(Widget.kt:46)
	at dev.mooner.starlight.ui.widget.config.WidgetsAdapter.onDestroy(WidgetsAdapter.kt:72)
	at dev.mooner.starlight.ui.home.HomeFragment.onDestroyView(HomeFragment.kt:141)
	at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3337)
	at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:745)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:327)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at androidx.viewpager2.adapter.FragmentStateAdapter.removeFragment(FragmentStateAdapter.java:464)
	at androidx.viewpager2.adapter.FragmentStateAdapter.gcFragments(FragmentStateAdapter.java:228)
	at androidx.viewpager2.adapter.FragmentStateAdapter$4.run(FragmentStateAdapter.java:580)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

──────────

대충 이런 경위입니다..ㅠㅠ

이거는 버그중의 버그겠죠..?

**Comment by mooner1022** [comment]
첨부해주신 위젯 Lifecycle 관련 문제를 수정한 버전[(다운로드)](https://cdn.discordapp.com/attachments/1106997962879545364/1145043952312004628/StarLight-0.1.0a-230827-release.apk)을 업로드했습니다. 해당 버전에서 다시 테스트 부탁드립니다.

**Comment by IntelPentium0** [comment]
> 첨부해주신 위젯 Lifecycle 관련 문제를 수정한 버전[(다운로드)](https://cdn.discordapp.com/attachments/1106997962879545364/1145043952312004628/StarLight-0.1.0a-230827-release.apk)을 업로드했습니다. 해당 버전에서 다시 테스트 부탁드립니다.

별빛이 정상적으로 들어가지는것을 확인완료 하였습니다.

![Screenshot_20230827-034343_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/c3785c60-8cba-420e-9a9d-31a75e50ebe3)


디버깅룸이 정상작동 하는것을 확인완료 하였습니다.

![Screenshot_20230827-033933_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/257ffba8-b034-4ff1-8b69-b2d8037a63a9)

카카오톡 문자도 정상적으로 보내지는것을 확인하였습니다.

![1693075199137](https://github.com/mooner1022/StarLight/assets/143253283/65036682-8eec-498e-9159-22820588618f)

늦은밤에도 오류 수정하시느라 고생많으셨습니다..!
