### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#25]
*** 치명적인 오류가 발생했습니다. 앱을 종료하는 중... ***
[버그 제보시 아래 메세지를 첨부해주세요.]
──────────
StarLight v0.1.0a-230827(build 1)
PluginCore v0.1.0
Build.VERSION.SDK_INT: 33
Build.DEVICE: gta4xlwifi
thread  : main
message : Unregistered event: dev.mooner.starlight.listener.event.OnNotificationPostedEvent
cause   : null
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.IllegalStateException: Unregistered event: dev.mooner.starlight.listener.event.OnNotificationPostedEvent
	at dev.mooner.starlight.listener.NotificationListener.onNotificationPosted(NotificationListener.kt:329)
	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:456)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2352)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

──────────

**Comment by mooner1022** [comment]
c2baece26ef3faf977e793eb9f51c38514401b2a 커밋에서 수정되었습니다. 하던 거 마저 수정하고 새 빌드 배포하겠습니다. 감사합니다.
