### ISSUE TITLE
StarLight v0.1.0a-230903 Error

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#29]
**치명적인 오류가 발생했습니다. 앱을 종료하는 중...
[버그 제보시 아래 메세지를 첨부해주세요.]**
```
StarLight v0.1.0a-230903(build 1)
PluginCore v0.1.0
Build.VERSION.SDK_INT: 33
Build.DEVICE: gta4xlwifi
thread  : DefaultDispatcher-worker-8
message : Failed to allocate a 16 byte allocation with 839826 free bytes and 820KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
cause   : null
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 839826 free bytes and 820KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at dev.mooner.starlight.plugincore.logger.internal.Logger$log$1.invokeSuspend(Logger.kt:129)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5cfca0e, LimitedDispatcher@4264bc5]
```

**Comment by mooner1022** [comment]
수정사항은 v0.2.0 릴리스에 통합되어 배포될 예정입니다. 제보해주셔서 감사합니다.
