### ISSUE TITLE
StarLight v0.2.0a-231221 Error

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#30]
**치명적인 오류가 발생했습니다. 앱을 종료하는 중...
[버그 제보시 아래 메세지를 첨부해주세요.]**
```
StarLight v0.2.0a-231221(build 2)
PluginCore v0.2.0
Build.VERSION.SDK_INT: 33
Build.DEVICE: gta4xlwifi
thread  : main
message : java.lang.reflect.InvocationTargetException
cause   : java.lang.reflect.InvocationTargetException
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	... 1 more
Caused by: java.lang.Exception: Expected error created from dev mode
	at dev.mooner.starlight.ui.settings.dev.DevModeActivityKt$startDevModeActivity$1$1$1$3$2.invoke(DevModeActivity.kt:61)
	at dev.mooner.starlight.ui.settings.dev.DevModeActivityKt$startDevModeActivity$1$1$1$3$2.invoke(DevModeActivity.kt:60)
	at dev.mooner.starlight.ui.config.CategoryRecyclerAdapter.onBindViewHolder$lambda$11(CategoryRecyclerAdapter.kt:263)
	at dev.mooner.starlight.ui.config.CategoryRecyclerAdapter.$r8$lambda$SvdHa6RXrtKDi7eUYjXyiSTs3hM(Unknown Source:0)
	at dev.mooner.starlight.ui.config.CategoryRecyclerAdapter$$ExternalSyntheticLambda3.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7912)
	at android.view.View.performClickInternal(View.java:7889)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31082)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	... 3 more
```

**Comment by seunghyun0934** [comment]
Occurs when the error button in developer mode is pressed incorrectly.
