### ISSUE TITLE
Project alignment issues

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#34]
Error log that occurs when sorting projects
```
               StarLight v0.2.0a-240208(build 2)
               PluginCore v0.2.0
               Build.VERSION.SDK_INT: 31
               Build.DEVICE: d1x
               thread  : main
               message : Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
ViewHolder 1:BindingViewHolder{58cf25c position=4 id=1087354647, oldPos=-1, pLpos:-1} 
View Holder 2:BindingViewHolder{d03acd0 position=3 id=1087354647, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{45b401e VFED..... ......ID 0,0-1006,1793 #7f0a0252 app:id/recyclerViewProjectList}, adapter:com.mikepenz.fastadapter.FastAdapter@2dac75d, layout:androidx.recyclerview.widget.LinearLayoutManager@e5548ac, context:dev.mooner.starlight.MainActivity@6f1d031
               cause   : null
               ┉┉┉┉┉┉┉┉┉┉
               Stack Trace:
               java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:BindingViewHolder{58cf25c position=4 id=1087354647, oldPos=-1, pLpos:-1} 
 View Holder 2:BindingViewHolder{d03acd0 position=3 id=1087354647, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{45b401e VFED..... ......ID 0,0-1006,1793 #7f0a0252 app:id/recyclerViewProjectList}, adapter:com.mikepenz.fastadapter.FastAdapter@2dac75d, layout:androidx.recyclerview.widget.LinearLayoutManager@e5548ac, context:dev.mooner.starlight.MainActivity@6f1d031
	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4778)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4702)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4367)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1331)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4614)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4036)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

──────────
```

**Comment by mooner1022** [comment]
혹시 프로젝트에 커스텀 버튼 사용하시나요?

**Comment by seunghyun0934** [comment]
네

**Comment by mooner1022** [comment]
[웹사이트](https://starlight.mooner.dev/)에 게재된 최신 버전(0.2.1)으로 다시 테스트 부탁드립니다.

**Comment by mooner1022** [comment]
Closing due to inactivity.
