### ISSUE TITLE
Inconsistency detected. Invalid item position

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#38]
```
──────────
StarLight v0.2.1a-240209(build 3)
PluginCore v0.2.0
Build.VERSION.SDK_INT: 31
Build.DEVICE: d1x
thread  : main
message : Inconsistency detected. Invalid item position 100(offset:100).state:117 androidx.recyclerview.widget.RecyclerView{984c425 VFED..... ........ 0,0-1006,1862 #7f0a0251 app:id/recyclerViewLogs}, adapter:dev.mooner.starlight.ui.logs.LogsRecyclerViewAdapter@87384f0, layout:androidx.recyclerview.widget.LinearLayoutManager@73794a4, context:dev.mooner.starlight.MainActivity@715dfb2
cause   : null
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 100(offset:100).state:117 androidx.recyclerview.widget.RecyclerView{984c425 VFED..... ........ 0,0-1006,1862 #7f0a0251 app:id/recyclerViewLogs}, adapter:dev.mooner.starlight.ui.logs.LogsRecyclerViewAdapter@87384f0, layout:androidx.recyclerview.widget.LinearLayoutManager@73794a4, context:dev.mooner.starlight.MainActivity@715dfb2
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6821)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

──────────
```

**Comment by mooner1022** [comment]
해당 오류가 발생한 상황이나 맥락도 추가해주세요.

**Comment by mooner1022** [comment]
Closing due to inactivity. Please feel free to reopen it if you have any further updates or questions.
