### ISSUE TITLE
삭제한 프로젝트가 다시 뜨는 오류

### ISSUE THREAD

**Issue by thfzm** [mooner1022/StarLight#48]
프로젝트 삭제 후 프로젝트들을 정렬하면 삭제한 프로젝트가 다시 뜨고 그 프로젝트에 상호작용을 하면 앱이 크래쉬가 납니다.

+앱은 다시 실행하면 되는데 컴파일 하는 과정이 조금 번거로워 모든 프로젝트를 컴파일하고 활성화 상태로 만들어주는 기능이 있으면 좋겠네요

**Comment by mooner1022** [comment]
크래쉬 후 재시작시 표시되는 에러 로그도 함께 첨부해주세요

**Comment by thfzm** [comment]
*** 치명적인 오류가 발생했습니다. 앱을 종료하는 중... ***
[버그 제보시 아래 메세지를 첨부해주세요.]
──────────
StarLight v0.3.1a-240815(build 5)
PluginCore v0.3.0
Build.VERSION.SDK_INT: 31
Build.DEVICE: d2x
thread  : DefaultDispatcher-worker-9
message : /storage/emulated/0/StarLight/projects/asdf/project.json: open failed: ENOENT (No such file or directory)
cause   : android.system.ErrnoException: open failed: ENOENT (No such file or directory)
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.io.FileNotFoundException: /storage/emulated/0/StarLight/projects/asdf/project.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
	at dev.mooner.starlight.plugincore.project.ProjectImpl$saveInfo$1.invokeSuspend$writeText(ProjectImpl.kt:226)
	at dev.mooner.starlight.plugincore.project.ProjectImpl$saveInfo$1.access$invokeSuspend$writeText(Unknown Source:0)
	at dev.mooner.starlight.plugincore.project.ProjectImpl$saveInfo$1$1.invoke(ProjectImpl.kt:226)
	at dev.mooner.starlight.plugincore.project.ProjectImpl$saveInfo$1$1.invoke(ProjectImpl.kt:226)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:219)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$flowOf$$inlined$unsafeFlow$2.collect(SafeCollector.common.kt:112)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:112)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:26)
	at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
	at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend(Collect.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@25919d4, Dispatchers.IO]
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8611)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 23 more

──────────
입니다

**Comment by mooner1022** [comment]
752aded3416ae8c789f9102fe14c4020a7a7fc1c 에서 수정되었습니다. 제보 감사합니다 🙂

**Comment by thfzm** [comment]
0.3.2 버전으로 업데이트 후 그걸 해봤는데

*** 치명적인 오류가 발생했습니다. 앱을 종료하는 중... ***
[버그 제보시 아래 메세지를 첨부해주세요.]
──────────
StarLight v0.3.1a-240815(build 5)
PluginCore v0.3.0
Build.VERSION.SDK_INT: 31
Build.DEVICE: d2x
thread  : main
message : Need to declare android.permission.REQUEST_INSTALL_PACKAGES to call this api
cause   : android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.canRequestPackageInstallsInternal(PackageManagerService.java:35325)
	at com.android.server.pm.PackageManagerService.canRequestPackageInstalls(PackageManagerService.java:35294)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4589)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9936)
	at android.os.Binder.execTransactInternal(Binder.java:1215)

┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.SecurityException: Need to declare android.permission.REQUEST_INSTALL_PACKAGES to call this api
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
	at android.os.Parcel.createException(Parcel.java:2422)
	at android.os.Parcel.readException(Parcel.java:2405)
	at android.os.Parcel.readException(Parcel.java:2347)
	at android.content.pm.IPackageManager$Stub$Proxy.canRequestPackageInstalls(IPackageManager.java:9992)
	at android.app.ApplicationPackageManager.canRequestPackageInstalls(ApplicationPackageManager.java:3925)
	at dev.mooner.starlight.ui.settings.update.CheckUpdateActivityKt$checkUpdate$3$7$1$1.invokeSuspend(CheckUpdateActivity.kt:256)
	at dev.mooner.starlight.ui.settings.update.CheckUpdateActivityKt$checkUpdate$3$7$1$1.invoke(Unknown Source:8)
	at dev.mooner.starlight.ui.settings.update.CheckUpdateActivityKt$checkUpdate$3$7$1$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:219)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:392)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3c80210, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.canRequestPackageInstallsInternal(PackageManagerService.java:35325)
	at com.android.server.pm.PackageManagerService.canRequestPackageInstalls(PackageManagerService.java:35294)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4589)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9936)
	at android.os.Binder.execTransactInternal(Binder.java:1215)


──────────


아직 앱이 크래쉬가 납니다

**Comment by jisungbin** [comment]
@thfzm 새로운 주제이므로 별도의 이슈로 공유해 주세요.
