### ISSUE TITLE
간헐적 프로젝트 컴파일 에러 현상

### ISSUE THREAD

**Issue by bgyooPtr** [mooner1022/StarLight#54]
PC에서 작업하고 USB 케이블로 파일 복붙 작업으로 진행중입니다.
간헐적으로 컴파일하면 이런 에러가 발생하고, 그 뒤 프로젝트 설정에서 프로젝트 스코프 폐기를 하면 다음과 같은 에러가 나타납니다.
그 뒤 에러 메시지와 함께 계속하기를 하면 정상 컴파일이 됩니다.

```txt
2024-12-27 16:40:40.692    INFO [DefaultDispatcher-worker-2 ] -      ProjectListItem: 봇 컴파일 실패
java.lang.NoSuchMethodError: No interface method removeFirst()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
```
프로젝트 스코프 폐기 누르고 앱이 멈춘뒤 나타나는 메시지
```
*** 치명적인 오류가 발생했습니다. 앱을 종료하는 중... ***
[버그 제보시 아래 메세지를 첨부해주세요.]
──────────
StarLight v0.3.2a-build_BWUVJM_nightly(build 100011)
PluginCore v0.3.0
Build.VERSION.SDK_INT: 34
Build.DEVICE: gts9
thread  : main
message : No interface method removeFirst()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
cause   : null
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
java.lang.NoSuchMethodError: No interface method removeFirst()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
	at dev.mooner.starlight.plugincore.logger.ProjectLogger.log(ProjectLogger.kt:132)
	at dev.mooner.starlight.plugincore.logger.ProjectLogger.v(ProjectLogger.kt:46)
	at dev.mooner.starlight.plugincore.logger.ProjectLogger.v(ProjectLogger.kt:43)
	at dev.mooner.starlight.plugincore.project.ProjectImpl.destroy(ProjectImpl.kt:262)
	at dev.mooner.starlight.ui.projects.config.ProjectConfigActivity.getStruct$lambda$75$lambda$74$lambda$73$lambda$66$lambda$64(ProjectConfigActivity.kt:372)
	at dev.mooner.starlight.ui.projects.config.ProjectConfigActivity.$r8$lambda$SyqluHN7IbqeQjIT_HB-qAauxig(Unknown Source:0)
	at dev.mooner.starlight.ui.projects.config.ProjectConfigActivity$$ExternalSyntheticLambda53.invoke(D8$$SyntheticClass:0)
	at dev.mooner.configdsl.options.ButtonConfigOption.onDraw$lambda$0(ButtonConfigOption.kt:52)
	at dev.mooner.configdsl.options.ButtonConfigOption.$r8$lambda$CAztGbO2fTl1ES25q2OSr4WztFk(Unknown Source:0)
	at dev.mooner.configdsl.options.ButtonConfigOption$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8055)
	at android.view.View.performClickInternal(View.java:8032)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31923)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

──────────
```

**Comment by mooner1022** [comment]
안녕하세요. 이슈 제보 감사합니다.

제보주신 에러는 저 또한 최근 앱을 사용하면서 인지하였으나, 현재 군복무 중인 관계로 당장은 상세한 원인 분석이나 디버깅이 어려운 상황입니다.
따라서 본 에러의 원인 분석이나 수정은 휴가 일정에 따라 1월 중순 즈음에 진행 가능할 것 같습니다.

다만, 추측컨대 본 에러의 발생은 최신 스냅샷 빌드에 포함된 코드 중 하나와 연관이 되어 있는 걸로 보이며, 현재 [공식 사이트](https://starlight.mooner.dev)의 다운로드 가능한 버전을 안정화 버전으로 롤백 하였으니 번거로우시겠지만 해당 버전으로 재설치 후 사용 부탁드립니다.

추후 이 문제가 수정되었을 때 본 이슈에 알려드림과 함께 close 하겠습니다. 
프로젝트에 대한 관심과 제보 감사합니다 🙂

**Comment by mooner1022** [comment]
0b10e08c04e07fcac93708a8d262d6a6327414f0 에서 수정되었습니다.
버그 수정 이외에 안정 버전과의 차이는 없으니, 현재 사용중이신 버전 그대로 사용하셔도 무방합니다 🙂
