### ISSUE TITLE
[Error] 에러 메시지 공유

### ISSUE THREAD

**Issue by hahamini** [mooner1022/StarLight#56]
v8 엔진 사용중 발생한 에러.
기존 라이노엔진에서 잘되는 코드가 V8에서 에러가 발생.

사용 라이브러리는 java.io 와 jsoup.

관련해서 의심되는게 있으면 테스트 해드리겠습니다.

새해 복 많이 받으시고, 남은 군생활 ㅎㅇㅌ 하세요!
Happy new year~

```
2025-01-01 03:09:37.964 CRITICA [Project-fseason-worker-1   ] -   ApplicationSession: *** 치명적인 오류가 발생했습니다. 앱을 종료하는 중... ***
[버그 제보시 아래 메세지를 첨부해주세요.]
──────────
StarLight v0.3.2a-build_BWUVJM_nightly(build 100011)
PluginCore v0.3.0
Build.VERSION.SDK_INT: 34
Build.DEVICE: gts9
thread  : Project-fseason-worker-1
message : Fatal exception in coroutines machinery for DispatchedContinuation[java.util.concurrent.ScheduledThreadPoolExecutor@11b9552[Running, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1], Continuation at dev.mooner.starlight.plugincore.project.ProjectImpl$callFunction$1.invokeSuspend(ProjectImpl.kt)@e887caa]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
cause   : java.lang.NoSuchMethodError: No interface method removeFirst()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
┉┉┉┉┉┉┉┉┉┉
Stack Trace:
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[java.util.concurrent.ScheduledThreadPoolExecutor@11b9552[Running, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1], Continuation at dev.mooner.starlight.plugincore.project.ProjectImpl$callFunction$1.invokeSuspend(ProjectImpl.kt)@e887caa]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:132)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2add5dd, java.util.concurrent.ScheduledThreadPoolExecutor@11b9552[Running, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]]
Caused by: java.lang.NoSuchMethodError: No interface method removeFirst()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
	at dev.mooner.starlight.plugincore.logger.ProjectLogger.log(ProjectLogger.kt:132)
	at dev.mooner.starlight.plugincore.logger.ProjectLogger.v(ProjectLogger.kt:46)
	at dev.mooner.starlight.plugincore.logger.ProjectLogger.v(ProjectLogger.kt:43)
	at dev.mooner.starlight.plugincore.project.ProjectImpl.destroy(ProjectImpl.kt:262)
	at dev.mooner.starlight.plugincore.project.ProjectManager.purge$PluginCore_debug(ProjectManager.kt:117)
	at dev.mooner.starlight.plugincore.Session.shutdown(Session.kt:111)
	at dev.mooner.starlight.core.ApplicationSession.shutdown$app_debug(ApplicationSession.kt:179)
	at dev.mooner.starlight.core.ApplicationSession.setExceptionHandler$lambda$4(ApplicationSession.kt:237)
	at dev.mooner.starlight.core.ApplicationSession.$r8$lambda$3dTa2PsXL3a_fCSEgWZgcrHJ7rE(Unknown Source:0)
	at dev.mooner.starlight.core.ApplicationSession$$ExternalSyntheticLambda2.uncaughtException(D8$$SyntheticClass:0)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt.propagateExceptionFinalResort(CoroutineExceptionHandlerImpl.kt:31)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:48)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:30)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:191)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:222)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:946)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:894)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:859)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:98)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	... 6 more

──────────
```

**Comment by mooner1022** [comment]
제보 감사합니다 🙂

본 에러는 V8 플러그인과 관련된 문제가 아닌 앱의 문제이며, 저도 인지하고는 있지만, 현재 상황이 상황인지라 수정을 못하고 있습니다.
다만 에러의 원인이 최신 스냅샷 빌드(빌드 버전 1000xx)에서만 발생하는 것으로 확인되어 현재 [공식 홈페이지](https://starlight.mooner.dev)의 다운로드 링크를 문제가 생기기 이전 버전으로 변경 해두었으니, 번거로우시겠지만 해당 버전으로 앱 재설치 후 사용을 부탁드립니다.
(빌드 버전이 낮아진 관계로 앱 삭제 후 재설치 하셔야 합니다)

본 이슈는 해당 문제 해결 이후 close 하겠습니다.
프로젝트에 많은 관심 감사합니다.
새해 복 많이 받으세요 😊

**Comment by mooner1022** [comment]
0b10e08c04e07fcac93708a8d262d6a6327414f0 에서 수정되었습니다.
버그 수정 이외에 안정 버전과의 차이는 없으니, 현재 사용중이신 버전 그대로 사용하셔도 무방합니다 🙂
